name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: '0 0 * * *' # todos los días a medianoche UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Pacman SVG
        uses: yoshi389111/github-pacman-graph@main
        with:
          username: moyeta-tech
          color_snake: '#facc15'         # color del pacman (amarillo)
          color_dots: '#d4d4d8'          # color de los puntitos
          color_blank: '#1e293b'         # color de fondo (oscuro)
          color_background: '#0f172a'    # color fondo total (oscuro)
          gif: false                     # true si querés gif, false si solo svg

      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: ./dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
