name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Pacman SVG
        uses: yoshi389111/github-pacman-graph@main
        with:
          username: moyeta-tech
          color_snake: '#facc15'
          color_dots: '#d4d4d8'
          color_blank: '#1e293b'
          color_background: '#0f172a'
          gif: false

      - name: Commit files
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add dist || echo "No files to add"
          git commit -m "Update pacman contribution graph" || echo "No changes to commit"
        continue-on-error: true

      - name: Push to GitHub Pages (output branch)
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
